services:
  - type: web
    name: pathways-3d-learning
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm install --legacy-peer-deps && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20.17.0
      - key: NODE_ENV
        value: production

