export function exportStudyPackToMarkdown({
  topic,
  modules,
}: {
  topic: string
  modules: Array<{
    title: string
    description: string
    lessons: Array<{
      title: string
      videoId: string
      channelTitle: string
      estimatedDuration: string
      summary?: { overview: string; takeaways: string[] } | null
    }>
  }>
}) {
  const date = new Date().toLocaleDateString("en-US", {
    year: "numeric",
    month: "long",
    day: "numeric",
  })

  let md = `# 📚 ${topic} — Complete AI Study Pack & Masterclass Syllabus\n`
  md += `*Generated by Pathways 3D Spatial AI Engine on ${date}*\n\n`
  md += `---\n\n`

  md += `## 🎯 Curriculum Overview\n`
  md += `This comprehensive study guide compiles verified YouTube masterclasses, deep AI key takeaways, cheat-sheet notes, and personal scratchpads for **${topic}**.\n\n`

  modules.forEach((mod, modIdx) => {
    md += `### 📂 Phase 0${modIdx + 1}: ${mod.title}\n`
    md += `*${mod.description}*\n\n`

    mod.lessons.forEach((lesson, lessonIdx) => {
      const isLikelyYT = typeof lesson.videoId === "string" && /^[a-zA-Z0-9_-]{11}$/.test(lesson.videoId)
      const ytLink = isLikelyYT
        ? `https://www.youtube.com/watch?v=${lesson.videoId}`
        : `https://www.youtube.com/results?search_query=${encodeURIComponent(lesson.title)}`

      md += `#### 🎬 Lesson ${modIdx + 1}.${lessonIdx + 1}: ${lesson.title}\n`
      md += `- **Creator / Channel:** ${lesson.channelTitle}\n`
      md += `- **Estimated Duration:** ${lesson.estimatedDuration}\n`
      md += `- **Video Link:** [Watch Tutorial on YouTube](${ytLink})\n\n`

      if (lesson.summary) {
        md += `##### 💡 AI Executive Overview\n`
        md += `${lesson.summary.overview}\n\n`

        md += `##### ✦ Core Technical Takeaways\n`
        lesson.summary.takeaways.forEach((t) => {
          md += `- ${t}\n`
        })
        md += `\n`
      }

      // Check if user has personal notes stored
      if (typeof window !== "undefined") {
        const userNote = localStorage.getItem(`pathways:note:${lesson.videoId}`)
        if (userNote) {
          md += `##### 📝 My Personal Notes & Timestamps\n`
          md += `> ${userNote.replace(/\n/g, "\n> ")}\n\n`
        }
      }

      md += `---\n\n`
    })
  })

  md += `\n## 🚀 Next Steps & Practice\n`
  md += `1. Review each lesson's core takeaways.\n`
  md += `2. Build a standalone prototype applying the principles.\n`
  md += `3. Test active recall using the Pathways 3D Quiz Arena.\n\n`
  md += `*Happy Learning! 🌟*\n`

  // Trigger browser download
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8;" })
  const url = URL.createObjectURL(blob)
  const link = document.createElement("a")
  link.setAttribute("href", url)
  link.setAttribute("download", `${topic.toLowerCase().replace(/[^a-z0-9]/g, "-")}-study-pack.md`)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}
